###
GET http://localhost:8000/

###
GET http://localhost:8000/users

###
GET http://localhost:8000/users/1

###
GET http://localhost:8000/users/3

###
POST http://localhost:8000/users
Content-Type: application/json

{
  "username": "test_user",
  "email": "test@example.com",
  "remark": "这是一个测试用户"
}

###
PUT http://localhost:8000/users/3
Content-Type: application/json

{
  "username": "updated_user",
  "email": "updated@example.com",
  "remark": "这是一个更新后的测试用户"
}

###
DELETE http://localhost:8000/users/3
